---
title: title: "Moses Samnahyia UI/UX Designer"
date: 2022-07-24
---
theme: minima
title: title: "Moses Samnahyia UI/UX Designer"
author: starlabelgh
date: 2022-07-24
email: hello@starlabel.co
description: > # this means to ignore newlines until "baseurl:"
  I am Moses Samanhyia, a UI/UX Designer and Front-End Developer.
  I have passion for developing user-centered user interfaces that gives the best user experience.
  Let's talk about system designs and best practices.

# social links
starlabelgh: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
starlabelgh:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
